#
# Common configuration variables for all environments
# being deployed to Kubernetes.
#
app_name: chippy

##########################

k8s_context: arn:aws:eks:us-east-1:472354598015:cluster/caktus-saguaro-cluster
eks_registry: "472354598015.dkr.ecr.us-east-1.amazonaws.com"
k8s_cluster_name: "caktus-saguaro-cluster"
k8s_container_image: "{{ eks_registry }}/chippy"

k8s_auth_host: "https://A9ED894F5721970831AED9882203CA29.gr7.us-east-1.eks.amazonaws.com"
k8s_auth_ssl_ca_cert: "k8s_auth_ssl_ca_cert.txt"

##############################

k8s_namespace: "{{ app_name }}-{{ env_name }}"
# we run migrations in docker-entrypoint.sh, so turn them off here
k8s_migrations_enabled: false
k8s_collectstatic_enabled: false
